name: Generate and Deploy API Docs

on:
  push:
    branches: [ "main" ]
    paths: 
      - '**/*.yaml' # или  '**/*.json' - указываем путь к нашему спеканию
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: ./openapi.yml  # Укажи свой путь!

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./swagger-ui

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
